version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: app_database
    environment:
      POSTGRES_DB: georegistry_db
      POSTGRES_USER: georegistry_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: georegistry_app
    ports:
      - "8081:8081"
    depends_on:
      - db