CREATE TABLE IF NOT EXISTS obec (
    id SERIAL PRIMARY KEY,
    kod INTEGER UNIQUE,
    nazev VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS cast_obce (
    id SERIAL PRIMARY KEY,
    kod INTEGER,
    nazev VARCHAR(255) NOT NULL,
    obec_kod INTEGER REFERENCES obec(kod) ON DELETE CASCADE
);