CREATE TABLE IF NOT EXISTS obec (
    kod SERIAL PRIMARY KEY,
    nazev VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS cast_obce (
    kod SERIAL PRIMARY KEY,
    nazev VARCHAR(255) NOT NULL,
    obec_kod INTEGER REFERENCES obec(kod) ON DELETE CASCADE
);
